apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
  labels:
    app: flask-todo
spec:
  selector:
    app: flask-todo
  ports:
    - name: http
      port: 5000        # service port inside cluster
      targetPort: 5000  # containerPort from deployment
  type: ClusterIP
