apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-todo.fullname" . }}
  labels:
    {{- include "flask-todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 5000
    protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "flask-todo.selectorLabels" . | nindent 4 }}
